plugins {
    alias(uiLibs.plugins.android.library)
    alias(uiLibs.plugins.kotlin.android)
    alias(uiLibs.plugins.kotlin.kapt)
}

android {
    namespace = 'eu.pretix.libpretixui.android'

    compileSdk = 36

    defaultConfig {
        minSdk = 23
        targetSdk = 36
        multiDexEnabled = true

        vectorDrawables {
            useSupportLibrary = true
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled = true
    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
    buildFeatures {
        buildConfig = true
        dataBinding = true
        viewBinding = true
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://jitpack.io' }
}

dependencies {
    coreLibraryDesugaring uiLibs.desugar.jdk.libs

    implementation uiLibs.kotlin.stdlib
    implementation uiLibs.nv.i18n
    implementation uiLibs.joda.time
    implementation uiLibs.android.phone.field
    implementation uiLibs.androidx.coreKtx
    implementation uiLibs.androidx.appcompat
    implementation uiLibs.androidx.constraintlayout
    implementation uiLibs.androidx.lifecycle.common
    implementation uiLibs.androidx.lifecycle.extensions1
    implementation uiLibs.zxing
    implementation uiLibs.androidx.camera.core
    implementation uiLibs.androidx.camera2
    implementation uiLibs.androidx.camera.lifecycle
    implementation uiLibs.androidx.camera.view
    implementation uiLibs.androidx.swiperefreshlayout
    implementation uiLibs.material
    implementation uiLibs.jsonLogicKotlin
    implementation uiLibs.androidx.preferenceKtx

    implementation implementation(project(':android-libuvccamera',))
    implementation implementation(project(':android-libusbcameracommon',))

    implementation(project(':libpretixsync')) {
        transitive = false
    }

    implementation uiLibs.glide
    kapt uiLibs.glide.compiler
}

