pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        maven {
            url = 'https://plugins.gradle.org/m2/'
        }
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        uiLibs {
            from(files("gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = 'eu.pretix.libpretixui-android'

include ':libpretixsync', ':android-libusbcameracommon', ':android-libuvccamera'
project(':libpretixsync').projectDir = new File('../../../libpretixsync-repo/libpretixsync')
project(':android-libusbcameracommon').projectDir = new File('../android-libusbcameracommon')
project(':android-libuvccamera').projectDir = new File('../android-libuvccamera')